### ISSUE TITLE
oitg.fitting.sinusoid unit tests fail

### ISSUE THREAD

**Issue by dnadlinger** [OxfordIonTrapGroup/oitg#17]
As per the title; specifically `test_delayed_split_data_with_t_dead` fails deterministically: https://circleci.com/gh/OxfordIonTrapGroup/oitg/84

**Comment by dnadlinger** [comment]
(This wasn't caught before because the fitting tests weren't actually executed on the CI system.)

**Comment by pathfinder49** [comment]
Hm, it worked when I ran them on my machine... I'll look into it.

**Comment by dnadlinger** [comment]
Fails on my local macOS box too (SciPy 1.2.1) – can let you have a look tomorrow if unreproducible on your end. (You can also SSH into CircleCI's machines, I believe.)

**Comment by pathfinder49** [comment]
Did they fail before the latest sinusoid commit? I coult imagine that violating the "fourier" limit might mess lombscargle around.

**Comment by pathfinder49** [comment]
Turns out the test is working fine. relaxing the Fourier limit makes the fitting fail the test.
