### ISSUE TITLE
Calculateing Binomial Data-Point Confidence Interval

### ISSUE THREAD

**Issue by pathfinder49** [OxfordIonTrapGroup/oitg#23]
There should be a function calculating the confidence interval for a binomial data-point. (for plotting purposes)

[This post](https://stackoverflow.com/a/19285227) seems to suggest the right thing. 

Broken out from [this issue](https://github.com/OxfordIonTrapGroup/oitg/issues/10)

**Comment by dnadlinger** [comment]
>  the right thing

This can be a bit tricky to define – see e.g. the already existing [oitg.errorbars](https://github.com/OxfordIonTrapGroup/oitg/blob/master/oitg/errorbars.py), which I believe Chris wrote.

**Comment by dnadlinger** [comment]
Closing as `oitg.errorbars` seems to do the job (at least without more detailed specification on the desired model).
