### ISSUE TITLE
Error for Loading results

### ISSUE THREAD

**Issue by sbrudney** [OxfordIonTrapGroup/oitg#37]
https://github.com/OxfordIonTrapGroup/oitg/blob/768b2d5be8cf189b192d025877518a227171177f/oitg/rid_index.py#L33

Is this line supposed to be "!=" or "=" instead of ":="? Changing to "!=" allows me to load results, while leaving it as is gives an error.

**Comment by dnadlinger** [comment]
This is the "walrus operator", introduced in Python 3.8.

**Comment by dnadlinger** [comment]
(https://docs.python.org/3/whatsnew/3.8.html#assignment-expressions)

**Comment by sbrudney** [comment]
I tried it with python 3.8 and it works fine. Thank you!
