### ISSUE TITLE
Robust sinc^2-like frequency scan fit for arbitrary pulse areas

### ISSUE THREAD

**Issue by dnadlinger** [OxfordIonTrapGroup/oitg#9]
It would be nice to have a robust way of fitting the spectra from scanning over a two-level-like transition with constant pulse area (i.e. sinc^2-like if area is exactly π).

I expect this to be a bit flaky if both pulse area and upper/lower levels are floated, but the user could always constrain these for better convergence.

**Comment by pathfinder49** [comment]
I've already started looking at this.

**Comment by pathfinder49** [comment]
What are your exact requirements?

The full relation for arbitary pulse area, detuning and rabi frequency is:

>     P_transfer = omega^2 * t_pulse^2 /4 * sinc^2(W*t_pulse/2)
>     where W = sqrt(omega^2 + (detuning+offset)^2)
if we do a detuning scan, the following parameters relate to these properties:
feature width - t_pulse
feature shape - omega 
feature position - offset

To account for errors you'd want something like: 
> a*omega^2 * t_pulse^2 /4 * sinc^2(W*t_pulse/2) + y0

does this cover your needs?

**Comment by dnadlinger** [comment]
At first glance, yes, something like that. As always, the real work will be in making the heuristics work sensibly on actual non-ideal data.

**Comment by pathfinder49** [comment]
[Done](https://github.com/OxfordIonTrapGroup/oitg/commit/3e511500f589d754157e5672e8c70640b0272349)
